// <auto-generated />
using System;
using ForgetTheBookie.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForgetTheBookie.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231222081423_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForgetTheBookie.Database.Model.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Odds")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProposedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Stake")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("EventId");

                    b.HasIndex("ProposedByUserId");

                    b.ToTable("Bet");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Team1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Team2Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Team1Id");

                    b.HasIndex("Team2Id");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("League");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Team1Goals")
                        .HasColumnType("integer");

                    b.Property<int?>("Team2Goals")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinningTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("WinningTeamId");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("BetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TransactionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BetId");

                    b.HasIndex("UserId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.UserBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserBalance");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.Bet", b =>
                {
                    b.HasOne("ForgetTheBookie.Database.Model.User", "AcceptedByUser")
                        .WithMany("AcceptedBets")
                        .HasForeignKey("AcceptedByUserId");

                    b.HasOne("ForgetTheBookie.Database.Model.Event", "Event")
                        .WithMany("Bets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForgetTheBookie.Database.Model.User", "ProposedByUser")
                        .WithMany("ProposedBets")
                        .HasForeignKey("ProposedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptedByUser");

                    b.Navigation("Event");

                    b.Navigation("ProposedByUser");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.Event", b =>
                {
                    b.HasOne("ForgetTheBookie.Database.Model.Team", "Team1")
                        .WithMany("EventsAsTeam1")
                        .HasForeignKey("Team1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForgetTheBookie.Database.Model.Team", "Team2")
                        .WithMany("EventsAsTeam2")
                        .HasForeignKey("Team2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team1");

                    b.Navigation("Team2");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.Result", b =>
                {
                    b.HasOne("ForgetTheBookie.Database.Model.Event", "Event")
                        .WithOne("Result")
                        .HasForeignKey("ForgetTheBookie.Database.Model.Result", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForgetTheBookie.Database.Model.Team", "Team")
                        .WithMany("Results")
                        .HasForeignKey("WinningTeamId");

                    b.Navigation("Event");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.Team", b =>
                {
                    b.HasOne("ForgetTheBookie.Database.Model.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.Transaction", b =>
                {
                    b.HasOne("ForgetTheBookie.Database.Model.Bet", "Bet")
                        .WithMany("Transactions")
                        .HasForeignKey("BetId");

                    b.HasOne("ForgetTheBookie.Database.Model.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.UserBalance", b =>
                {
                    b.HasOne("ForgetTheBookie.Database.Model.User", "User")
                        .WithOne("UserBalance")
                        .HasForeignKey("ForgetTheBookie.Database.Model.UserBalance", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.Bet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.Event", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("Result")
                        .IsRequired();
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.Team", b =>
                {
                    b.Navigation("EventsAsTeam1");

                    b.Navigation("EventsAsTeam2");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("ForgetTheBookie.Database.Model.User", b =>
                {
                    b.Navigation("AcceptedBets");

                    b.Navigation("ProposedBets");

                    b.Navigation("Transactions");

                    b.Navigation("UserBalance")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
