/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../../public/assets/css/nucleo-icons.css";
import "../../public/assets/css/nucleo-svg.css";
import "../../public/assets/css/soft-ui-dashboard-tailwind.css";
import NavBar from "./components/Navbar";
import Footer from "./components/Footer";
import { Providers } from "./providers";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FTBookie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        /> */}
        <link rel="apple-touch-icon" sizes="76x76" href="/assets/img/apple-icon.png" />
        {/*     Fonts and icons     */}
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&display=swap" rel="stylesheet" />

        {/* Nucleo Icons */}
        {/* <link href="/assets/css/nucleo-icons.css" rel="stylesheet" />
        <link href="/assets/css/nucleo-svg.css" rel="stylesheet" /> */}

        {/* Font Awesome Icons */}
        <script src="https://kit.fontawesome.com/42d5adcbca.js" crossOrigin="anonymous" async></script>

        {/* Main Styling */}
        <link href="/assets/css/soft-ui-dashboard-tailwind.css?v=1.0.1" rel="stylesheet" />

        {/* Nepcha Analytics (nepcha.com) */}
        {/* Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. */}
      </head>
      <body
        suppressHydrationWarning={true}
        className={`${inter.className} h-screen m-0 font-sans text-base antialiased font-normal text-left leading-default dark:bg-slate-950 bg-gray-50 text-slate-500 dark:text-white`}
      >
        <Providers>
          <main className="relative h-full max-h-screen transition-all duration-200 ease-soft-in-out rounded-xl">
            <NavBar />

            {/* <Suspense fallback={<Loading />}> */}
            <section className="container pb-10">
              <div className="w-full mx-auto pt-[5rem] container">{children}</div>
            </section>
            {/* </Suspense> */}

            <section>
              <Footer />
            </section>

            {/* <section className="container py-10">{children}</section>

            <section>
              <Footer />
            </section> */}
          </main>

          {/* <UIConfigurator /> */}
        </Providers>
      </body>
    </html>
  );
}
